### ISSUE TITLE
Binary generated from package definition is not reliable

### ISSUE THREAD

**Issue by ymeine** [ariatemplates/editor-backend#36]
[npm](https://npmjs.org) provides a feature to define [binaries](https://npmjs.org/doc/json.html#bin), especially useful when installing a package globally, as a classical program.

This project uses this feature, and defines a binary that should launch the backend server (equivalent of doing `npm start`).

However the documentation on this is not really clear. Apparently, you can specify a binary only by providing a path to a file. Here this is what is done and when the package is installed, the generated binary tries only to execute directly the specified path, with the default OS action associated to the type of the pointed file.

So here it's launching a `.js` file, which usually is not configured to run with node.

When looking at other projects for which this is working, they apparently all define their binaries by: 
- pointing to a file without any extension
- putting at the top of this file a [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) 

The documentation doesn't tell it, but I guess that the key of the issue is the shebang, since npm is close to Unix philosophy, and shebangs are completely tied to the concept of executable (binaries). I think that when generating the binary npm reads the shebang to adapt its script on the target OS.

**Comment by piuccio** [comment]
You might find this article worth reading
http://joesul.li/van/2013/08/npm-bin.html

In short
- use `#!/usr/bin/env node`
- save the file with **Unix** line feed.

The second point is my addition, but it's necessary when you push to npm and expect the program to be used on all platforms.

**Comment by ymeine** [comment]
Thanks Fabio! I tried it and it actually works, even though the doc still doesn't tell it (the article you linked points it out too)

However, for the line endings, I don't really know how it is handled. I need to check my git configuration, but I think my checked out files have Windows line endings, but they are converted to Unix line endings when committed.

Anyway I'm not publishing it on npm for now. And if I would need to put this package as a dependency of another I would use [git urls](https://npmjs.org/doc/json.html#Git-URLs-as-Dependencies).

But if I ever publish it with npm, I guess it's using my local files, right? So you mean I would need to change the line endings of my binary scripts before doing [`npm publish`](https://npmjs.org/doc/cli/npm-publish.html), every time? (maybe a [`prepublish`](https://npmjs.org/doc/misc/npm-scripts.html) script would however ease this process)

**Comment by piuccio** [comment]
Yes, npm uses your local files, I think however that it's enough to change line ending once. Git will not mark the file as changed if you have auto crlf.
